version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  apt_packages:
    - gfortran
  jobs:
    pre_build:
      - python docs/markdown_builder.py --output docs/camb_docs_combined.md

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py

formats: all

submodules:
  include: all
